trigger:
  - master  # Триггер на коммиты в ветку master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'web-cicd'  # Use the correct service connection name
      appType: 'webApp'  # Specify the application type
      appName: 'web-cicd'  # Replace with your Azure App Service name
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'  # Path to the deployment package
