trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'web-cicd'  # Replace with the correct name of your Azure subscription
      appName: 'web-cicd'  # Replace with your Azure App Service name
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      enableCustomDeployment: true
