trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover -s tests
  displayName: 'Run tests'

- script: |
    zip -r $(Build.ArtifactStagingDirectory)/myapp.zip *
  displayName: 'Archive files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'web-cicd'
    appType: webAppLinux
    appName: 'web-cicd'
    package: '$(Build.ArtifactStagingDirectory)/myapp.zip'






