trigger:
  - master  # Trigger on commits to the master branch

pool:
  vmImage: ubuntu-latest

steps:
  # Step 1: Checkout the code from GitHub
  - checkout: self
    clean: true

  # Step 2: Use the specific .NET SDK version (adjust the version as needed)
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x.x'  # Specify the desired .NET SDK version (e.g., 6.x.x for .NET 6)
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Step 3: Restore dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'  # Ensure this pattern matches your project files

  # Step 4: Build the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'  # Ensure this pattern matches your project files

  # Step 5: Publish the project (create the deployment package)
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'  # Ensure this pattern matches your project files
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  # Step 6: Publish the build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to publish
      ArtifactName: 'drop'  # Name of the artifact
      publishLocation: 'Container'

  # Step 7: Deploy the artifact to Azure Web App
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'web-cicd'  # Use the correct service connection name
      appType: 'webApp'  # Specify the application type
      appName: 'web-cicd'  # Replace with your Azure App Service name
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'  # Path to the deployment package
